"""Explicații concise — metode de cercetare (itemi 51–100, ID 10051–10100)."""

from __future__ import annotations

from typing import List

METODE_CERCETARE_EXPLANATIONS: List[str] = [
    "Adevărat. Longitudinalul urmărește aceiași oameni în timp, deci vezi schimbarea reală la aceeași persoană. Costă mai mult și participanții pot abandona studiul.",
    "Corect: aceiași participanți (a), traiectorie individuală (b), attrition (d). Greșit: longitudinalul nu e mereu mai rapid/ieftin — transversalul e de obicei mai rapid (c).",
    "Aceiași copii la 7, 9 și 11 ani = longitudinal (a). Transversalul ar compara grupe diferite o singură dată, fără urmărire în timp.",
    "Adevărat. Transversalul compară vârste la același moment; diferențele pot veni și din generație/cohortă, nu doar din vârstă.",
    "Corect: a, c, d. Greșit b — inversează avantajele: longitudinalul e lent și scump, transversalul nu urmărește aceiași copii.",
    "Compari o dată copii de vârste și generații diferite → risc efect de cohortă (a), nu validitate internă experimentală.",
    "Longitudinal: schimbare reală, dar cost în timp (a). Transversal: rapid, dar cohortă (b). c și d inversează metodele.",
    "Concluzia e plauzibilă, dar transversalul nu elimină explicația alternativă prin cohortă — deci prudență (a).",
    "Studiul de caz merge în profunzime pe puține cazuri (a). Nu generalizează automat la toată populația (b greșit).",
    "Corect: profunzime (a), util pentru cazuri rare (b), date bogate calitative (d). c e capcană — generalizarea largă e redusă.",
    "Un singur copil urmărit detaliat = studiu de caz (a), nu transversal sau experiment pe grupuri mari.",
    "Adevărat. În experiment manipulezi variabila independentă și poți vorbi mai clar despre cauză; uneori situația e artificială.",
    "Corect: manipulare (a), inferențe cauzale (b), posibilă artificialitate (d). Nu are mereu validitate ecologică maximă (c).",
    "Randomizare + program vs. fără program = experiment (a): manipulare și comparare de grupuri.",
    "Experiment: manipulare și control (a, c). Observație naturală: realism, dar control redus (d). b e fals.",
    "Comportament diferit în lab vs. acasă = problemă de validitate externă/ecologică (a), nu lipsa validității interne.",
    "Interviul aduce experiența raportată (a). Nu elimină subiectivitatea (c fals); întrebările pot modela răspunsul (d).",
    "Corect: a, b, d. Interviul accesează subiectivitatea și are formate variate; răspunsurile pot fi modelate de întrebări. c e fals — biasul nu dispare.",
    "Observație în context real + validitate ecologică mare (a, b). Controlul experimental nu e maxim (c, d greșite).",
    "Corect: a, c, d. Interviu = raportat; observație = context real; subiectivitate la interviu; ecologică mare și control redus la observație. b e fals.",
    "Notezi joaca fără intervenție în grădiniță = observație naturală (a).",
    "Interviul depinde de memorie și formularea întrebărilor (a) — mai mult decât observația directă a comportamentului.",
    "Interviu: bogăție, dar subiectivitate (a). Observație naturală: realism, control redus (b).",
    "Discrepanță interviu vs. observație = limitele raportului subiectiv (a); de aceea combinăm surse de date.",
    "Corect: a, d — integrare interviu, observație și analiză; înțelegerea dinamicii personale. b și c descriu sondajul, nu clinica.",
    "Corect: a, b, c — interviu, observație, analiză de context. d e scop de sondaj național, nu metodă clinică.",
    "Istoric + observație + interviu integrat = metodă clinică (a).",
    "Clinica = profunzime pe caz (a, b, d). Sondajul = frecvențe în populații mari — nu e același scop (c fals).",
    "Falsă este a: metodele clinice folosesc interviul și observația. Restul sunt afirmații adevărate despre clinica.",
    "Corect: a, b, d. Etica și consimțământul rămân obligatorii — clinica nu le înlocuiește (c).",
    "Observație la joc + interviu cu mama = tipic metode clinice combinate (a).",
    "Capcana: generalizare automată de la un caz la toți copiii (a). Integrarea surselor e o practică bună, nu o capcană.",
    "Adevărat. La copii: consimțământ, protecție, confidențialitate, scop clar și risc minim.",
    "Corect: consimțământ și scop clar (a), protecție (b), confidențialitate (c). Ascunderea scopului e neetică (d).",
    "Fără acord parental și cu nume publicate = lipsă consimțământ (a) și confidențialitate (b).",
    "Fals. Durata scurtă nu elimină consimțământul informat la copii.",
    "Corect: explicare pe înțelesul copilului (a), retragere fără pedeapsă (b), anonimizare (d). Stres major nejustificat e neetic (c).",
    "Informarea părinților despre scop și drept de retragere = consimțământ informat (a).",
    "Toate patru perechi corecte: longitudinal, transversal, experiment, studiu de caz (a–d).",
    "Orice metodă cere protecția copilului (a, b, d). Ascunderea scopului e neetică (c).",
    "„Același copil în timp” → longitudinal (a).",
    "„Diferă 6 vs. 10 ani măsurați acum” → transversal (a).",
    "„Programul X cauzează îmbunătățirea” → experiment cu control (a).",
    "Situație rară, trăită în profunzime → studiu de caz (a).",
    "Corect: attrition/cohortă (a), artificialitate/control (b), subiectivitate/generalizare (c). Consimțământul nu dispare la clinica (d).",
    "Rapiditatea transversalului e reală (a), dar nu elimină cohorta; attrition e la longitudinal (d). b și c sunt false.",
    "Capcane false: a, b, c. Interviul poate fi util știind limitele subiectivității (d adevărat).",
    "Profunzime: studiu de caz, metode clinice, interviu+observație clinică (a, b, d). Sondaj național = frecvență, nu profunzime (c).",
    "Checklist etic: consimțământ, confidențialitate, risc minim (a, b, c). Ascunderea intenției e greșită (d).",
    "Grilă corectă: longitudinal/transversal, experiment/observație, interviu/observație (a–c). Etica nu e opțională (d fals).",
]

assert len(METODE_CERCETARE_EXPLANATIONS) == 50
